### PR TITLE
Added optional parameter setptr

### PR DESCRIPTION
**Pull request by congiohj**

### CODE REVIEW

**Comment by anuriq** [comment]
Hi @congiohj 
By any chance, have you seen https://github.com/terraform-providers/terraform-provider-powerdns/pull/4 ?

**Comment by congiohj** [comment]
Hi @anuriq,

I haden't seen #4 when I created this merge request. Should I close it ? I actually use #4 in production. Also, do you think issues #4 and #7 will be merge with master one day ?

**Comment by anuriq** [comment]
there is a vacant position of maintainer of this repo right now. i think no actions are needed, until there will be a maintainer

**Comment by mbag** [comment]
@congiohj  thanks for the PR, but as @anuriq mentioned, he had opened PR #4 adding the same parameter, and also included documentation and individual test case, so I merged his PR into the master.

Looking forward to your future PRs, since this provider has been un-archived and will be activelly developed by @splashx  and I.

**Pull request closed without merging**
