### PR TITLE
Use Go modules; upgrade deps for Terraform v0.12

### PR DESCRIPTION
**Pull request by andreykaipov**
First off thank you @mbag and @splashx for unarchiving this provider 😄

Here's the steps I took:
```
go mod init
go clean -modcache
go get github.com/hashicorp/terraform@v0.12
go mod tidy
go mod vendor
```

After building and moving the provider to one of the discoverable plugin locations, I was able to get it working with Terraform v0.12.

### CODE REVIEW

**Comment by andreykaipov** [comment]
Also tested this with Terraform v0.11 and it still works!

**Comment by mbag** [comment]
hi @andreykaipov  thanks for the PR,

I'm still waiting for an access to Hashicorp's Terraform TeamCity testing environment. Even though this repository has Travis tests, the TF TeamCity tests will be decisive. I'll merge/get back to you regarding changes, once I know what kind of tests are required by TF to consider provider migrated.

In the mean time, it was my mistake not creating PR with test fixes, can you create independent PR, instead of it being part of this PR? I'm referring to this commit: https://github.com/terraform-providers/terraform-provider-powerdns/pull/16/commits/4a65a018c4284952113e3eaa8e63e1616cf65d8e

Once again thank you for taking time to work on PowerDNS provider.

**Comment by loksonarius** [comment]
I like this ❤️

**Comment by andreykaipov** [comment]
Hi @mbag - sounds good to me! Looking forward to hearing how that goes.

I've removed the test fix commit from this PR and opened https://github.com/terraform-providers/terraform-provider-powerdns/pull/17 in its place.

**Pull request merged**
